print("Exercise A")
print("Looks like {1} and {0} for brakfast".format("eggs", "spam"))
print()
print("------------------------------------------------------------")
print("Exercise B")
# print("There is {0}{1}{2}{3}".format(!, " spam", 4, " you"))
print()
print("------------------------------------------------------------")
print("Exercise c")
print("Hello {0}".format("Susan", "Computewell"))
print()
print("------------------------------------------------------------")
print("Exercise D")
print("{0:0.2f} {0:0.2f}".format(2.3 , 2.3468))
print()
print("------------------------------------------------------------")
# print("Exercise E")
# print("{7.5f} {7.5f}".format(1, 37.374))
# print()
# print("------------------------------------------------------------")
print("Exercise F")
print("Time left {0:02f}:{1:05.2f}".format(1 , 37.374))
print()
print("------------------------------------------------------------")
print("Exercise G")
#print("{1:3}".format("14"))