print()
print("Show the output that would be generated by of the following program fragments")
print()
print("A")
for ch in "aardvark":
    print(ch)

print("===================================================")
print("B")
for w in "Now is winter of our discontent....".split():
    print(w)

print("===================================================")
print("C")
for w in "Mississippi".split("i"):
    print(w, end=" ")
    #print(w)
print()
print("===================================================")
print("D")
msg = ""
for s in "secret".split("e"):
    msg = msg + s
print(msg)

print("===================================================")
print("E")
msg = ""
for ch in "secret": 
    msg = msg + chr(ord(ch)+ 1)
print(msg)


